/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package qlpt;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class HopDong extends javax.swing.JFrame {

    /**
     * Creates new form HopDong
     */
    public HopDong() {
        initComponents();
        setLocationRelativeTo(null);
        loadTable();
        hopDongDAO.loadPhongToComboBox(cbxPhong);
        hopDongDAO.loadKhachHangToComboBox(cbxKhachHang);
    }

    HopDongDAO hopDongDAO = new HopDongDAO();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnLap = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtNgayLap = new javax.swing.JTextField();
        txtHinhAnh = new javax.swing.JTextField();
        txtThoiHan = new javax.swing.JTextField();
        txtSoLuongXe = new javax.swing.JTextField();
        btnSua = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHopDong = new javax.swing.JTable();
        btnChonAnh = new javax.swing.JButton();
        cbxKhachHang = new javax.swing.JComboBox<>();
        cbxPhong = new javax.swing.JComboBox<>();
        txtTienCoc = new javax.swing.JTextField();
        txtSoNguoi = new javax.swing.JTextField();
        cbxTrangThai = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("HỢP ĐỒNG THUÊ PHÒNG TRỌ");

        jLabel2.setText("Phòng");

        jLabel3.setText("Khách Hàng");

        jLabel4.setText("Tiền Cọc: ");

        jLabel5.setText("Thời Hạn Thuê: ");

        jLabel6.setText("Số Người: ");

        jLabel8.setText("Trạng Thái:");

        jLabel9.setText("Ngày lập: ");

        jLabel10.setText("Số Lượng Xe: ");

        btnLap.setText("Lập");
        btnLap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLapActionPerformed(evt);
            }
        });

        btnHuy.setText("Xoá");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        jLabel11.setText("Hình Ảnh Đính Kèm:");

        txtNgayLap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayLapActionPerformed(evt);
            }
        });

        txtThoiHan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThoiHanActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        tblHopDong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Hợp Đồng", "Phòng", "Khách Hàng", "Căn Cước", "Ngày Lập", "Tiền Cọc", "Thời Hạn", "Số Người Ở", "SoLuongXe", "Trạng Thái", "Hình Ảnh Đính Kèm", "ID Phòng", "ID Khách Hàng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false, true, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHopDong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHopDongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHopDong);

        btnChonAnh.setText("...");

        cbxKhachHang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxKhachHangItemStateChanged(evt);
            }
        });

        cbxPhong.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxPhongItemStateChanged(evt);
            }
        });

        txtTienCoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTienCocActionPerformed(evt);
            }
        });

        txtSoNguoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoNguoiActionPerformed(evt);
            }
        });

        cbxTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Còn Thời Hạn", "Hết Thời Hạn" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btnLap, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHuy))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(55, 55, 55)
                                .addComponent(cbxPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(142, 142, 142))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnChonAnh))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel3)
                                                    .addComponent(jLabel4))
                                                .addGap(55, 55, 55)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(cbxKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGap(0, 0, Short.MAX_VALUE))
                                                    .addComponent(txtTienCoc)))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(cbxTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(89, 89, 89)))
                                .addGap(56, 56, 56)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(30, 30, 30)
                                .addComponent(txtThoiHan, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addGap(30, 30, 30)
                                    .addComponent(txtNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel10)
                                    .addGap(30, 30, 30)
                                    .addComponent(txtSoLuongXe, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel6))
                            .addComponent(txtSoNguoi, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(126, 126, 126))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jLabel6, jLabel8});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel10, jLabel5, jLabel9});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnHuy, btnLap});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(cbxKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(txtThoiHan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(txtSoLuongXe, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cbxPhong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtTienCoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtSoNguoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(cbxTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtHinhAnh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChonAnh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHuy, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLap, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLapActionPerformed(java.awt.event.ActionEvent evt) {
        // Kiểm tra dữ liệu nhập
        if (txtTienCoc.getText().trim().isEmpty() || txtThoiHan.getText().trim().isEmpty()
                || txtSoNguoi.getText().trim().isEmpty() || txtSoLuongXe.getText().trim().isEmpty()
                || txtNgayLap.getText().trim().isEmpty() || cbxTrangThai.getSelectedItem() == null
                || cbxPhong.getSelectedItem() == null || cbxKhachHang.getSelectedItem() == null) {

            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!", "Lỗi",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            // Lấy dữ liệu từ giao diện
            String ngayLapText = txtNgayLap.getText().trim(); // Người dùng nhập dd/MM/yyyy
            String ThoiHanText = txtThoiHan.getText().trim();
            // Kiểm tra định dạng ngày
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            java.util.Date thoiHan;
            java.util.Date ngayDateLap; // Định nghĩa như là java.util.Date
            try {
                ngayDateLap = sdf.parse(ngayLapText);
                thoiHan = sdf.parse(ThoiHanText);
            } catch (ParseException e) {
                JOptionPane.showMessageDialog(this, "Ngày không hợp lệ! Định dạng đúng: dd/MM/yyyy",
                        "Lỗi",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Chuyển java.util.Date thành java.sql.Date
            java.sql.Date sqlDateNgayLap = new java.sql.Date(ngayDateLap.getTime());
            java.sql.Date sqlDateThoiHan = new java.sql.Date(thoiHan.getTime());

            String tienCoc = txtTienCoc.getText().trim();

            int soNguoiO = Integer.parseInt(txtSoNguoi.getText().trim());
            int soLuongXe = Integer.parseInt(txtSoLuongXe.getText().trim());
            String trangThai = cbxTrangThai.getSelectedItem().toString();
            String hinhAnh = txtHinhAnh.getText().trim();

            // Gọi hàm thêm hợp đồng vào CSDL
            hopDongDAO.themHopDong(idPhong, idKhachHang, sqlDateNgayLap, tienCoc, sqlDateThoiHan, soNguoiO,
                    soLuongXe,
                    trangThai, hinhAnh);
            loadTable();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Số người ở và số lượng xe phải là số nguyên!",
                    "Lỗi nhập liệu",
                    JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi thêm hợp đồng: " + e.getMessage(), "Lỗi",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
    // GEN-LAST:event_btnLapActionPerformed

    private void loadTable() {
        hopDongDAO.loadHopDongData(tblHopDong);
    }

    private void txtNgayLapActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtNgayLapActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtNgayLapActionPerformed

    private void txtThoiHanActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtThoiHanActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtThoiHanActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {
        // Kiểm tra dữ liệu nhập
        if (txtTienCoc.getText().trim().isEmpty() || txtThoiHan.getText().trim().isEmpty()
                || txtSoNguoi.getText().trim().isEmpty() || txtSoLuongXe.getText().trim().isEmpty()
                || txtNgayLap.getText().trim().isEmpty() || cbxTrangThai.getSelectedItem() == null
                || cbxPhong.getSelectedItem() == null || cbxKhachHang.getSelectedItem() == null) {

            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin!", "Lỗi",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {

            // Lấy dữ liệu từ giao diện
            String ngayLapText = txtNgayLap.getText().trim(); // Định dạng dd/MM/yyyy
            String thoiHanText = txtThoiHan.getText().trim();

            // Chuyển đổi ngày tháng
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            java.util.Date ngayDateLap;
            java.util.Date thoiHan;
            try {
                ngayDateLap = sdf.parse(ngayLapText);
                thoiHan = sdf.parse(thoiHanText);
            } catch (ParseException e) {
                JOptionPane.showMessageDialog(this, "Ngày không hợp lệ! Định dạng đúng: dd/MM/yyyy",
                        "Lỗi",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Chuyển java.util.Date thành java.sql.Date
            java.sql.Date sqlDateNgayLap = new java.sql.Date(ngayDateLap.getTime());
            java.sql.Date sqlDateThoiHan = new java.sql.Date(thoiHan.getTime());

            // Lấy dữ liệu khác
            String tienCoc = txtTienCoc.getText().trim();
            int soNguoiO = Integer.parseInt(txtSoNguoi.getText().trim());
            int soLuongXe = Integer.parseInt(txtSoLuongXe.getText().trim());
            String trangThai = cbxTrangThai.getSelectedItem().toString();
            String hinhAnh = txtHinhAnh.getText().trim();

            // Gọi hàm cập nhật hợp đồng trong CSDL
            hopDongDAO.suaHopDong(idHopDong, idPhong, idKhachHang, sqlDateNgayLap, tienCoc, sqlDateThoiHan,
                    soNguoiO, soLuongXe, trangThai, hinhAnh);
            loadTable();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Lỗi định dạng số! Số người ở và số lượng xe phải là số nguyên.",
                    "Lỗi nhập liệu",
                    JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi khi cập nhật hợp đồng: " + e.getMessage(), "Lỗi",
                    JOptionPane.ERROR_MESSAGE);
        }
    }
    // GEN-LAST:event_btnSuaActionPerformed

    private void txtTienCocActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtTienCocActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtTienCocActionPerformed

    private void txtSoNguoiActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtSoNguoiActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtSoNguoiActionPerformed

    private boolean isFirstChangePhong = true;
    private int idPhong;
    private int idKhachHang;

    private void cbxPhongItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_cbxPhongItemStateChanged
        if (isFirstChangePhong) {
            isFirstChangePhong = false;
            return;
        }
        idPhong = hopDongDAO.getSelectedPhongID(cbxPhong);
        System.out.println("id phong " + idPhong);
    }// GEN-LAST:event_cbxPhongItemStateChanged

    private boolean isFirstChangeKhachHang = true;

    private void cbxKhachHangItemStateChanged(java.awt.event.ItemEvent evt) {// GEN-FIRST:event_cbxKhachHangItemStateChanged
        if (isFirstChangePhong) {
            isFirstChangePhong = false;
            return;
        }
        idKhachHang = hopDongDAO.getSelectedKhachHangID(cbxKhachHang);
        System.out.println("id Khach " + idKhachHang);
    }// GEN-LAST:event_cbxKhachHangItemStateChanged

    private int idHopDong; // Lưu ID hợp đồng

    private void tblHopDongMouseClicked(java.awt.event.MouseEvent evt) {
        int selectedRow = tblHopDong.getSelectedRow();
        if (selectedRow == -1) {
            return; // Không chọn dòng nào
        }

        // Lấy mô hình bảng
        DefaultTableModel model = (DefaultTableModel) tblHopDong.getModel();

        // Lưu ID hợp đồng vào biến idHopDong
        idHopDong = Integer.parseInt(model.getValueAt(selectedRow, 0).toString());

        // Đổ dữ liệu vào JTextField
        txtTienCoc.setText(model.getValueAt(selectedRow, 5).toString()); // Tiền cọc
        txtThoiHan.setText(model.getValueAt(selectedRow, 6).toString()); // Thời hạn
        txtSoNguoi.setText(model.getValueAt(selectedRow, 7).toString()); // Số người ở
        txtSoLuongXe.setText(model.getValueAt(selectedRow, 8).toString()); // Số lượng xe

        // Sửa lỗi: JComboBox không có setText(), phải dùng setSelectedItem()
        cbxTrangThai.setSelectedItem(model.getValueAt(selectedRow, 9).toString()); // Trạng thái hợp đồng

        // Định dạng ngày
        String ngayLap = model.getValueAt(selectedRow, 4).toString(); // Ngày lập (định dạng dd/MM/yyyy)
        txtNgayLap.setText(ngayLap);

        // Xử lý hình ảnh đính kèm nếu cần
        String hinhAnh = model.getValueAt(selectedRow, 10) != null
                ? model.getValueAt(selectedRow, 10).toString()
                : "";
        txtHinhAnh.setText(hinhAnh); // Hiển thị đường dẫn hình ảnh (nếu có)

        // Lấy tên phòng và CCCD từ bảng (cột 1 và 3)
        String tenPhong = model.getValueAt(selectedRow, 1).toString();
        String cccd = model.getValueAt(selectedRow, 3).toString();

        // Lấy ID từ HashMap và cập nhật JComboBox
        cbxPhong.setSelectedItem(tenPhong);
        cbxKhachHang.setSelectedItem(cccd);
        System.out.println("id hop dong " + idHopDong);
    }

    // GEN-LAST:event_tblHopDongMouseClicked
    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnHuyActionPerformed
        hopDongDAO.xoaHopDong(tblHopDong);
        loadTable();
    }// GEN-LAST:event_btnHuyActionPerformed

    @Override
    public void dispose() {
        // Khi cửa sổ QuanLyPhong đóng, mở lại TrangChinh
        TrangChu trangChinh = new TrangChu();
        trangChinh.setVisible(true); // Hiển thị lại TrangChinh
        super.dispose(); // Đảm bảo cửa sổ QuanLyPhong được đóng
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                    .getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HopDong.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HopDong.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HopDong.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HopDong.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HopDong().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChonAnh;
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnLap;
    private javax.swing.JButton btnSua;
    private javax.swing.JComboBox<String> cbxKhachHang;
    private javax.swing.JComboBox<String> cbxPhong;
    private javax.swing.JComboBox<String> cbxTrangThai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHopDong;
    private javax.swing.JTextField txtHinhAnh;
    private javax.swing.JTextField txtNgayLap;
    private javax.swing.JTextField txtSoLuongXe;
    private javax.swing.JTextField txtSoNguoi;
    private javax.swing.JTextField txtThoiHan;
    private javax.swing.JTextField txtTienCoc;
    // End of variables declaration//GEN-END:variables
}
